# Generated by Django 4.2.6 on 2023-11-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='event',
            field=models.IntegerField(),
        ),
    ]
